#include <sys/socket.h>
#include <iostream>
#include <netinet/in.h>//字节序转换
#include <arpa/inet.h>//IP地址转换
#include <string.h>
#include <sys/types.h>
#include <signal.h>
#include <unistd.h>
#include <assert.h>
#include <libgen.h>
#include <error.h>
#include <stdlib.h>